[package]
name = "sentencepiece"
version = "0.11.3"
authors = ["Daniël de Kok <me@danieldk.eu>"]
edition = "2018"
description = "Binding for the sentencepiece tokenizer"
repository = "https://github.com/danieldk/sentencepiece.git"
license = "MIT OR Apache-2.0"
exclude = ["testdata/albert-base-v1-spiece.model"]

[dependencies]
libc = "0.2"
num-derive = "0.4"
num-traits = "0.2"
prost = "0.14"
prost-derive = "0.14"
sentencepiece-sys = { path = "../sentencepiece-sys", version = "0.11.2" }
thiserror = "2"

[features]
albert-tests = []
system = ["sentencepiece-sys/system"]
static = ["sentencepiece-sys/static"]
