name: "Unit tests"

on: [push, pull_request]

jobs:
  without-sentencepiece:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable
        target-features:
          - "+crt-static"
          - "-crt-static"
    name: Test without libsentencepiece
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          override: true
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.toolchain }}-cargo-${{ hashFiles('**/Cargo.toml') }}-${{ matrix.target-features }}
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run tests (macOS)
        if: matrix.os == 'macos-latest'
        env:
          RUSTFLAGS: "-Ctarget-feature=${{ matrix.target-features }}"
        run: scripts/test-all.sh --target x86_64-apple-darwin
      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest' && matrix.target-features != '+crt-static'
        env:
          RUSTFLAGS: "-Ctarget-feature=${{ matrix.target-features }}"
        run: scripts/test-all.sh --target x86_64-unknown-linux-gnu
      - name: Run tests (Windows)
        env:
          RUSTFLAGS: "-Ctarget-feature=${{ matrix.target-features }}"
        if: matrix.os == 'windows-latest'
        run: scripts/test-all.ps1 --target x86_64-pc-windows-msvc
